spring:
  profiles:
    active: dev
  datasource:
    username: root
    password: Ufriends2022!
    driverClassName: org.mariadb.jdbc.Driver
    hikari:
      connectionTimeout: 30000
      maxLifetime: 290000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mariadb://ufriends.cua6kbojjeav.us-west-2.rds.amazonaws.com/ufriends

# ---
# spring:
#   profiles: real
#   datasource:
#     url:
