# spring MariaDB Connect
spring:
  datasource:
    tomcat:
        max-active: 5
        max-wait: 10000
    url: jdbc:mariadb://ufriends.cua6kbojjeav.us-west-2.rds.amazonaws.com/ufriends
    username: root
    password: Ufriends2022!
    driverClassName: org.mariadb.jdbc.Driver

  # data - jpa ??
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none