# spring MariaDB Connect
spring:
  datasource:
    url: jdbc:mariadb://ufriends.cua6kbojjeav.us-west-2.rds.amazonaws.com/ufriends
    username: root
    password: Ufriends2022!
    driverClassName: org.mariadb.jdbc.Driver
    hikari:
          connectionTimeout: 30000 #30000ms
          maxLifetime: 290000 #1800000ms(30?). maria db ??? 28800? (8??) -> ?? 1???? ??
  # data - jpa ??
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none