spring:
  profiles:
    active: dev
  datasource:
    username: admin
    password: Ufriends789!
    driverClassName: org.mariadb.jdbc.Driver
    hikari:
      connectionTimeout: 30000
      maxLifetime: 290000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mariadb://ufriends.cvtx7e9jgnfm.us-west-2.rds.amazonaws.com/ufriends

# ---
# spring:
#   profiles: real
#   datasource:
#     url:
