spring:
  profiles:
    active: local
  datasource:
    url:
    username:
    password:
    driverClassName: org.mariadb.jdbc.Driver
    hikari:
      connectionTimeout: 30000
      maxLifetime: 290000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update